apiVersion: 1

datasources:
  - name: SOC Elasticsearch
    uid: soc-elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    editable: true
    jsonData:
      index: soc-logs-*
      timeField: '@timestamp'
      interval: Daily
      esVersion: 8
