apiVersion: 1

datasources:
  - name: Elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    editable: false
    jsonData:
      index: soc-logs-*
      interval: Daily
      timeField: '@timestamp'
